version: '3.4'

services:
  mongo:
    image: mongo:5.0-focal
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
    networks:
      - mongodb-net
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: "redis:7.0-alpine"
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongodb-data:

networks:
  mongodb-net:
    driver: bridge